"""
Data models for the Agentic Trust Layer.
Follows PRD §7 Data Model exactly.
All monetary amounts are in paise (integers).
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from sqlmodel import SQLModel, Field


# ── Catalog ──────────────────────────────────────────────────────────────────

class Product(BaseModel):
    """A product in the merchant catalog."""
    id: str
    name: str
    price: int                  # paise
    category: str
    merchant_id: str


# ── Policy ───────────────────────────────────────────────────────────────────

class Policy(SQLModel, table=True):
    """What actually gets stored in the database."""
    id: Optional[int] = Field(default=None, primary_key=True)
    max_amount: int
    merchant_id: str
    allowed_categories: str               # stored as comma-separated string
    expires_at: datetime
    require_confirmation_above: Optional[int] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    active: bool = True

    def categories_list(self) -> list[str]:
        """Convert stored string back into a list when reading."""
        return [c.strip() for c in self.allowed_categories.split(",") if c.strip()]


# ── Agent ────────────────────────────────────────────────────────────────────

class Proposal(BaseModel):
    """Structured purchase proposal generated by the LLM."""
    product_id: str
    product_name: str
    amount: int                 # paise
    merchant_id: str
    category: str
    reasoning: str              # why the agent chose this product


class Decision(BaseModel):
    """Result of the deterministic policy evaluation."""
    allowed: bool
    reason: str
    rule_triggered: Optional[str] = None
    # possible values: "expiry" | "merchant" | "category" | "amount"
    #                  | "confirmation_required" | None


# ── Audit ────────────────────────────────────────────────────────────────────

class AuditEvent(SQLModel, table=True):
    """Immutable record of every state transition in the system."""
    id: Optional[int] = Field(default=None, primary_key=True)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    event_type: str
    # "intent" | "proposal" | "policy_check" | "payment_created"
    # | "payment_captured" | "payment_failed"
    payload: str                # JSON-encoded details


# ── Request / Response helpers ───────────────────────────────────────────────

class IntentRequest(BaseModel):
    """Incoming natural-language purchase request."""
    text: str


class IntentResponse(BaseModel):
    """Response containing the generated proposal and the policy evaluation decision."""
    proposal: Proposal
    decision: Decision


class PolicyCreateRequest(BaseModel):
    """What the user/frontend sends in."""
    max_amount: int                       # paise, e.g. 200000 = ₹2,000
    merchant_id: str
    allowed_categories: list[str]         # e.g. ["gifts", "groceries"]
    expires_at: datetime
    require_confirmation_above: Optional[int] = None
